=== ToliNety/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://javaops.ru" xmlns:lib="http://javaops.ru" elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element name="City" type="cityType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="Project">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name"/>
                                        <xs:element type="xs:string" name="description"/>
                                    </xs:sequence>
                                    <xs:attribute name="projid" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Groups">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="Group">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name"/>
                                    </xs:sequence>
                                    <xs:attribute type="groupStatus" name="status" use="required"/>
                                    <xs:attribute type="xs:string" name="project" use="required"/>
                                    <xs:attribute type="xs:ID" name="groupID" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
        <xs:key name="PK_Project">
            <xs:selector xpath="lib:Projects|lib:Project"/>
            <xs:field xpath="@projid"/>
        </xs:key>
        <xs:keyref name="FK_Group_Project" refer="PK_Project">
            <xs:selector xpath="lib:Groups|lib:Group"/>
            <xs:field xpath="@project"/>
        </xs:keyref>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
                <xs:element type="groupList" name="groups"/>
            </xs:sequence>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
            <xs:attribute type="xs:string" name="email" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="groupStatus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="groupList">
        <xs:list itemType="xs:IDREF"/>
    </xs:simpleType>
</xs:schema>

=== ToliNety/masterjava/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Projects>
        <Project name="topjava">
            <description>TopJava Project</description>
            <Groups>
                <Group name="topjava01" groupType="FINISHED"/>
                <Group name="topjava02" groupType="CURRENT"/>
                <Group name="topjava03" groupType="REGISTERING"/>
            </Groups>
        </Project>
        <Project name="masterjava">
            <description>MasterJava Project</description>
            <Groups>
                <Group name="masterjava01" groupType="CURRENT"/>
                <Group name="masterjava02" groupType="REGISTERING"/>
            </Groups>
        </Project>
    </Projects>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Users>
        <User flag="active" city="kiv" email="gmail1@gmail.com" groups="topjava02">User</User>
        <User flag="active" city="kiv" email="gmail2@gmail.com" groups="topjava01">User</User>
        <User flag="superuser" city="spb" email="admin@javaops.ru" groups="topjava03">Admin</User>
        <User flag="deleted" city="spb" email="mail@yandex.ru">Deleted</User>
    </Users>
</Payload>
